server:
  port: 0
  
spring:
  datasource:
    url: jdbc:hsqldb:file:./myLittleDB
    username: sa
  
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect 
    show-sql: false
    hibernate:
      ddl-auto: create

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5