info:
  component: Zuul Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "*"
  prefix: /api
  routes:
    card-statement-api: /card-state/**
    #card-extract-integration:
      #path: /card-extract-integration/**

server:
  port: 8765

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user


logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
